service: nodejs-websockets

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  memorySize: 256
  role: arn:aws:iam::accountnumber:role/rolename # includs cloud watch full access, Dynamo db access, apigateway access

functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket:
          route: $default
